import "./globals.scss";
import Header from "@/components/header/Header";
import Footer from "@/components/footer/Footer";
import { TaskProvider } from "../context/TaskContext";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">

      <body>
        <TaskProvider>
          <Header/>
          {children}
          <Footer/>
        </TaskProvider>
      </body>
    </html>
  );
}
